steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/wallet-payment-svc', '.']
    # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/wallet-payment-svc']
    # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'wallet-payment-svc', '--image', 'gcr.io/$PROJECT_ID/wallet-payment-svc', '--region', 'europe-west1','--platform', 'managed', '--allow-unauthenticated' ,'--quiet']
images:
  - gcr.io/$PROJECT_ID/wallet-payment-svc