openapi: 3.0.0
info:
  title: Wallet Payment Gateway Service
  version: 0.0.1
  description: |
    Wallet Payment Gateway Service is a REST HTTP API for handling payment. It exposes REST endpoint for

    # Responses

    ## HTTP Response Codes
    | Status Code | Usage                                                       |
    |-------------|-------------------------------------------------------------|
    | 200         | The request completed successfully                          |
    | 201         | A new resource has been created                             |
    | 400         | Malformed request                                           |
    | 401         | Missing access token                                        |
    | 403         | The client does not have permission to access this resource |
    | 404         | Resource not found                                          |
    | 405         | Method not supported                                        |
    | 500         | Internal server error                                       |
    | 503         | Service unvailable                                          |

    ## Errors
    whenever an error occured within the platform, an error response that describes the problem will be returned

    | Field Name        | Field Description     |
    |-------------------|-----------------------|
    | Status            | "fail" or "error"     |
    | StatusCode        | A business error code |
    | StatusDescription | Error description     |

    ## Error codes

    | Error Code | Error Description                                |
    |------------|--------------------------------------------------|
    | 10001      | Cash In request registered                       |

    # Changelog

    ## 2019-11-05
    * Created .....

    # Useful links
  termsOfService: 'http://swagger.io/terms/'
  x-logo:
    url: '/img/NBK_logo.jpeg'
    backgroundColor: '#FFFFFF'
    altText: NBK Logo
servers:
  - url: 'https://wallet-payment-svc-x6fr3lwlgq-nw.a.run.app/'
    description: Testing Server
  - url: 'http://localhost:8099'
    description: Local Server
tags:
  - name: Stripe Integration
    description: Uses Stripe API
  - name: MTN Integration
    description: MTN Integration
  - name: Paypal Integration
    description: Uses Paypal API
paths:
  /v1/stripe/payments/form/{amount}/{currency}/{accountId}:
    get:
      summary: Return a form
      tags:
        - Stripe Integration
      security:
        - oAuth2:
            - StripeCreatePaymentIntent
      parameters:
        - name: amount
          in: path
          required: true
          schema:
            type: number
            description: amount to top up
            example: 12
        - name: currency
          in: path
          required: true
          schema:
            type: string
            description: Currency
            example: USD
        - name: accountId
          in: path
          required: true
          schema:
            type: string
            description: Account to top up
            example: 5e6e9889f5aae9439c41757b
        - name: userId
          in: path
          required: true
          schema:
            type: string
            description: Account owner
            example: ui6e9889f5aae9439c41757f
      responses:
        '200':
          description: Successfully obtained card payment form
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Error when obtaining card payment form
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: fail
                statusCode: 4001
                statusDescription: Error when obtaining card payment form
  /v1/stripe/payments/intents/{accountId}:
    post:
      summary: Create a payment intent
      tags:
        - Stripe Integration
      security:
        - oAuth2:
            - MTNCashIn
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
            description: Wallet Account ID
            example: 5e6e9889f5aae9439c41757b
      requestBody:
        description: Payment Intent
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CashInRequest'
      responses:
        '201':
          description: Successfully created payment intent
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/ResponseStatus'
                  data:
                    type: object
                    properties:
                      CashIn:
                        $ref: '#/components/schemas/StripeCashInResponse'
        '500':
          description: Error when creating payment intent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: fail
                statusCode: 4010
                statusDescription: Error when creating payment intent
  /v1/mtn/payments/accounts/{accountId}/cash-out:
    post:
      summary: Create a cash out transaction
      tags:
        - MTN Integration
      security:
        - oAuth2:
            - MTNCashOut
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
            description: Wallet Account ID
            example: 5e6e9889f5aae9439c41757b
      requestBody:
        description: Cash Out Request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CashOutRequest'
      responses:
        '201':
          description: Successfully created cash out request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/ResponseStatus'
  /v1/mtn/payments/transactions/{transactionId}/cash-out:
    get:
      summary: Return transfer status
      tags:
        - MTN Integration
      security:
        - oAuth2:
            - MTNTransferGetStatus
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
            description: Transaction ID
            example: ui6e9889f5aae9439c41757f
      responses:
        '200':
          description: Successfully fetched transfer status
          content:
            text/html:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/ResponseStatus'
                  data:
                    type: object
                    properties:
                      CashOut:
                        type: object
                        properties:
                          transactionId:
                            type: string
                            example: 5e95b31b3a480d75ac0aa204
                          status:
                            type: string
                            enum:
                              - pending
                              - successful
                              - error
  /v1/mtn/payments/update-wallet-accounts/cash-out:
    get:
      summary: Settle Cash Out Operations
      tags:
        - MTN Integration
      responses:
        '200':
          description: Successfully updated wallet accounts
          content:
            text/html:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/ResponseStatus'
                  data:
                    type: object
                    properties:
                      WalletAccounts:
                        type: array
                        items:
                          type: object
                          properties:
                            accountId:
                              type: string
                              example: 5e95b31b3a480d75ac0aa204
  /v1/mtn/payments/update-wallet-accounts/cash-in:
    get:
      summary: Settle Cash In Operations
      tags:
        - MTN Integration
      responses:
        '200':
          description: Successfully updated wallet accounts
          content:
            text/html:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/ResponseStatus'
                  data:
                    type: object
                    properties:
                      WalletAccounts:
                        type: array
                        items:
                          type: object
                          properties:
                            accountId:
                              type: string
                              example: 5e95b31b3a480d75ac0aa204
  /v1/mtn/payments/transactions/{transactionId}/cash-in:
    get:
      summary: Return a request to pay status
      tags:
        - MTN Integration
      security:
        - oAuth2:
            - MTNRequestToPayGetStatus
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
            description: Transaction ID
            example: ui6e9889f5aae9439c41757f
      responses:
        '200':
          description: Successfully fetched request to pay status
          content:
            text/html:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/ResponseStatus'
                  data:
                    type: object
                    properties:
                      CashIn:
                        type: object
                        properties:
                          transactionId:
                            type: string
                            example: 5e95b31b3a480d75ac0aa204
                          status:
                            type: string
                            enum:
                              - pending
                              - successful
                              - error
  /v1/mtn/payments/accounts/{accountId}/cash-in:
    post:
      summary: Create a MTN cash in transaction
      tags:
        - MTN Integration
      security:
        - oAuth2:
            - MTNCashIn
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
            description: Wallet Account ID
            example: 5e6e9889f5aae9439c41757b
      requestBody:
        description: Cash In Request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CashInRequest'
      responses:
        '201':
          description: Successfully created cash in request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/ResponseStatus'
                  data:
                    type: object
                    properties:
                      CashIn:
                        type: object
                        properties:
                          transactionId:
                            type: string
                            example: 5e95b31b3a480d75ac0aa204
                          status:
                            type: string
                            enum:
                              - pending
                              - successful
                              - error
  /v1/paypal/payments/form/{amount}/{currency}/{accountId}/{userId}:
    get:
      summary: Return a form
      tags:
        - Paypal Integration
      security:
        - oAuth2:
            - PaypalCreateOrderPayment
      parameters:
        - name: amount
          in: path
          required: true
          schema:
            type: number
            description: amount to top up
            example: 12
        - name: currency
          in: path
          required: true
          schema:
            type: string
            description: Currency
            example: USD
        - name: accountId
          in: path
          required: true
          schema:
            type: string
            description: Account to top up
            example: 5e6e9889f5aae9439c41757b
        - name: userId
          in: path
          required: true
          schema:
            type: string
            description: UserId to top up
            example: 5e6bf1567127a743ad93e3b2
      responses:
        '200':
          description: Successfully obtained creating an order payment form
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Error when obtaining creating an order payment form
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: fail
                statusCode: 4001
                statusDescription: Error when obtaining creating an order payment payment form
  /v1/paypal/payments/execute/{accountId}:
    post:
      summary: Create an order payment
      tags:
        - Paypal Integration
      security:
        - oAuth2:
            - MTNCashIn
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
            description: Wallet Account ID
            example: 5e6e9889f5aae9439c41757b
      requestBody:
        description: Create Order for Payment
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaypalRequest'
      responses:
        '201':
          description: Successfully created payment intent
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/ResponseStatus'
                  data:
                    type: object
                    properties:
                      CashIn:
                        $ref: '#/components/schemas/PaypalCashInResponse'
        '500':
          description: Error when creating order payment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: fail
                statusCode: 4010
                statusDescription: Error when creating order payment
components:
  securitySchemes:
    oAuth2:
      type: oauth2
      description: This API uses OAuth 2 with the client credentials grant flow
      flows:
        clientCredentials:
          tokenUrl: https://nbk-wallet.auth.eu-west-1.amazoncognito.com/oauth2/token
          scopes:
            PaypalCreateOrderPayment: Create a Paypal order fo payment
            StripeCreatePaymentIntent: Create a Stripe Payment Intent
            MTNCashIn: MTN Cash In
            MTNCashOut: MTN Cash out
  schemas:
    ResponseStatus:
      type: string
      enum:
        - success
        - fail
        - error
    ErrorResponseStatus:
      type: string
      enum:
        - fail
        - error
    ResponseStatusCode:
      type: number
      example: 1023
    ResponseStatusDescription:
      type: string
      example: wallet event does not exist within the system
    ErrorResponse:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/ErrorResponseStatus'
        statusCode:
          $ref: '#/components/schemas/ResponseStatusCode'
        statusDescription:
          $ref: '#/components/schemas/ResponseStatusDescription'
    CashOutRequest:
      type: object
      properties:
        amount:
          $ref: '#/components/schemas/Amount'
        type:
          $ref: '#/components/schemas/CashInRequestType'
        currency:
          $ref: '#/components/schemas/Currency'
        originator:
          $ref: '#/components/schemas/Originator'
    CashInRequest:
      type: object
      properties:
        amount:
          $ref: '#/components/schemas/Amount'
        type:
          $ref: '#/components/schemas/CashInRequestType'
        currency:
          $ref: '#/components/schemas/Currency'
        originator:
          $ref: '#/components/schemas/Originator'
        description:
          $ref: '#/components/schemas/Description'
    Originator:
      type: object
      properties:
        originatorType:
          type: string
          enum:
            - User
            - Process
        originatorId:
          type: string
          example: 5e6bf1567127a743ad93e3b2
    StripeCashInResponse:
      type: object
      properties:
        transactionId:
          type: string
          example: 5e99a07063389569485205f3
        extras:
          type: object
          properties:
            clientSecret:
              type: string
              description: client secret
              example: pi_1GUXqnI7cAZaA1PNcmH7sYhO_secret_PIX3t9agUEFjSTtmcPU0EtnJu
            publishableKey:
              type: string
              description: Stripe plublishabe key
              example: pk_test_muG8jSMNY9OyPOQFCN3JtYMx00w4hXalgG
    PaypalRequest:
      type: object
      properties:
        amount:
          $ref: '#/components/schemas/Amount'
        type:
          type: string
          example: PAYPAL
        currency:
          $ref: '#/components/schemas/Currency'
        originator:
          $ref: '#/components/schemas/Originator'
        description:
          $ref: '#/components/schemas/Description'
        applicationContext:
          $ref: '#/components/schemas/ApplicationContext'
    PaypalCashInResponse:
      type: object
      properties:
        transactionId:
          type: string
          example: 5e99a07063389569485205f3
        amount:
          $ref: '#/components/schemas/Amount'
        status:
          type: string
          example: pending
        extras:
          type: object
          properties:
            approveUrl:
              type: string
              description: Approve Url
              example: https://www.sandbox.paypal.com/checkoutnow?token=6LS64528XG914772C
            orderId:
              type: string
              description: Oerder Identifiant
              example: 6LS64528XG914772C
            payerID:
              type: string
              description: Payer Identifiant
              example: U7AFM93EDQUMY
    Currency:
      type: string
      description: Currency
      enum:
        - EUR
        - USD
        - GBP
    CashInRequestType:
      type: string
      enum:
        - MTN
        - STRIPE
        - PAYPAL
        - OrangeMoney
        - BankAccount
    Amount:
      type: number
      description: amount to cash out
      example: 20
    Description:
      type: string
      description: transaction description
      example: Top Up
    ApplicationContext:
      type: object
      properties:
        successUrl:
          type: string
          description: Success Url
          example: https://your-domain/sucsess
        cancelOrFailUrl:
          type: string
          description: Cancel or fail Url
          example: https://your-domain/cancel
